Use ActivityCompat to check if permission is granted
There was an exception on pre-6.0 Android devices
`context.checkSelfPermission()` required API level 23

```
Caused by java.lang.NoSuchMethodError: No virtual method checkSelfPermission(Ljava/lang/String;)I in class Lcom/facebook/react/bridge/ReactApplicationContext; or its super classes
       at com.rt2zz.reactnativecontacts.ContactsManager.isPermissionGranted(ContactsManager.java:1221)
       at com.rt2zz.reactnativecontacts.ContactsManager.checkPermission(ContactsManager.java:1149)
       at java.lang.reflect.Method.invoke(Method.java)